name: MayaMelody
version: '1.0.0'
main: me.seedim.mayaMelody.MayaMelody
authors:
  - Seedim
description: Where Worlds Converge
api-version: '1.21'
dependencies:
  server:
    NoteBlockAPI:
      load: BEFORE
      required: true
